on:
  push:
  schedule:
    - cron: '0 0 */1 * *'
  workflow_dispatch:  

name: Test Registry

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: install docker
        if: ${{ false }}
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: "20.10"
          docker_channel: test
          docker_buildx: false
          
      - run: docker version
        if: ${{ false }}
      
      - run: docker info
        if: ${{ false }}   
      
      - name: install wget,gh
        run: sudo apt install -yq wget && wget -q https://github.com/cli/cli/releases/download/v2.14.3/gh_2.14.3_linux_amd64.tar.gz && tar xf gh_*.tar.gz && cp gh_*_linux_amd64/bin/gh /usr/local/bin/ && gh -
              
      - name: install yq
        run: gh release download --repo mikefarah/yq -p 'yq_linux_amd64' && mv yq_linux_amd64 /usr/local/bin/yq && chmod a+x /usr/local/bin/yq
      
      - name: get download url
        id: skopeo
        run: gh api repos/lework/skopeo-binary/releases/latest | yq -P '.assets[]|select(.browser_download_url=="*x86_64*").browser_download_url'

      - name: show download url
        run: echo ${{ steps.skopeo.outputs.data }}
      - uses: actions/checkout@v1
      
      - name: Run read-yaml action
        id: yaml-data
        uses: KJ002/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: './registry.yaml'          # File to read from
          key-path: '["registry", "hosts"]' # Access the runs key then the using key and retuns the value.

      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"
        
      - name: Test registry
        if: ${{ false }}
        run: |
          image="library/alpine"

          for registry in ${{steps.yaml-data.outputs.data }}
          do
             echo ::group::Test $registry/$image
             skopeo inspect docker://$registry/$image \
               && (echo -e "\033[32m$registry is good\033[0m" \
                  ; echo "::warning file=README.md,line=1,col=0::OK [ $registry ] is good") \
               || (echo -e "\033[31m$registry is outdated\033[0m" \
                  ; echo "::error file=README.md,line=1,col=0::X [ $registry ] is outdated")
             echo ::endgroup::
          done
